// <auto-generated />
using System;
using Agendai.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agendai.Data.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Agendai.Models.Entity", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Agendai.Models.Event", b =>
                {
                    b.HasBaseType("Agendai.Models.Entity");

                    b.Property<string>("AgendaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Due")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InitialDue")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Reminders")
                        .HasColumnType("TEXT");

                    b.Property<int>("Repeats")
                        .HasColumnType("INTEGER");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Agendai.Models.Shift", b =>
                {
                    b.HasBaseType("Agendai.Models.Entity");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Agendai.Models.Todo", b =>
                {
                    b.HasBaseType("Agendai.Models.Entity");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Due")
                        .HasColumnType("TEXT");

                    b.Property<uint>("FinishedShifts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InitialDue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListName")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Reminders")
                        .HasColumnType("TEXT");

                    b.Property<int>("Repeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TotalShifts")
                        .HasColumnType("INTEGER");

                    b.ToTable("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
